"""add rbac and telegram tables

Revision ID: 0686d7bc2a01
Revises: 7a4862701a03
Create Date: 2026-03-13 09:32:24.376769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0686d7bc2a01'
down_revision: Union[str, Sequence[str], None] = '7a4862701a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('bank_operations', 'import_batch_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.drop_constraint(op.f('fk_bank_operations_account'), 'bank_operations', type_='foreignkey')
    # op.drop_column('bank_operations', 'bank_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('bank_operations', sa.Column('bank_account_id', sa.UUID(), autoincrement=False, nullable=True))
    # op.create_foreign_key(op.f('fk_bank_operations_account'), 'bank_operations', 'bank_accounts', ['bank_account_id'], ['id'])
    # op.alter_column('bank_operations', 'import_batch_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    op.drop_table('user_roles')
    op.drop_table('telegram_accounts')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
