"""create new bank_operations structure

Revision ID: 5d1b36177f47
Revises: 5f209f7decfc
Create Date: 2026-03-01 23:58:20.953827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1b36177f47'
down_revision: Union[str, Sequence[str], None] = '5f209f7decfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('operation_date', sa.DateTime(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('counterparty_account', sa.String(), nullable=True),
    sa.Column('counterparty_inn', sa.String(), nullable=True),
    sa.Column('counterparty_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('operation_category', sa.String(), server_default='other', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'document_number', 'document_type', 'operation_date', 'amount', 'direction', name='uq_operation_identity')
    )
    op.create_index('idx_operation_company_date', 'bank_operations', ['company_id', 'operation_date'], unique=False)
    op.create_index('idx_operation_company_inn', 'bank_operations', ['company_id', 'counterparty_inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_operation_company_inn', table_name='bank_operations')
    op.drop_index('idx_operation_company_date', table_name='bank_operations')
    op.drop_table('bank_operations')
    # ### end Alembic commands ###
