"""add consent_id to bank_connections

Revision ID: 5ee7da6f867d
Revises: 05be4ed2d0e7
Create Date: 2026-03-06 16:12:28.142855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee7da6f867d'
down_revision: Union[str, Sequence[str], None] = '05be4ed2d0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_connections', sa.Column('consent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_connections', 'consent_id')
    # ### end Alembic commands ###
