"""add unique constraint to bank_operations

Revision ID: 5f209f7decfc
Revises: 5c39e5b110cd
Create Date: 2026-03-01 13:49:14.134803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f209f7decfc'
down_revision: Union[str, Sequence[str], None] = '5c39e5b110cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank_operations', ['company_id', 'bank_operation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_operations', type_='unique')
    # ### end Alembic commands ###
