"""add last_synced_at to bank_accounts

Revision ID: bff3debb657a
Revises: 54d688eaee27
Create Date: 2026-03-06 23:32:59.680814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff3debb657a'
down_revision: Union[str, Sequence[str], None] = '54d688eaee27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'last_synced_at')
    # ### end Alembic commands ###
