"""add last_synced_at to bank_connections

Revision ID: fa468ae2d01a
Revises: 5ee7da6f867d
Create Date: 2026-03-12 12:50:46.688316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa468ae2d01a'
down_revision: Union[str, Sequence[str], None] = '5ee7da6f867d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_connections', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_connections', 'last_synced_at')
    # ### end Alembic commands ###
